rendering
renderChannelOn: rss
	rss title: self config title.
	rss link: self config url.
	rss description: self config title.
	rss language english.
	"rss publicationDate: 'Tue, 10 Jun 2003 04:00:00 GMT'.
	rss lastBuildDate: 'Tue, 10 Jun 2003 09:41:01 GMT'."
	rss defaultDocumentation.
	rss generator: 'WorkLog 1.0'.
	"rss managingEditor: 'editor@example.com'.
	rss webMaster: 'webmaster@example.com'"