#! /bin/bash -e

PHARO_VM=pharo-sh
IMAGE=../worklog.image
CMD="$PHARO_VM $IMAGE worklog"
admin_option=

print_usage() {
	echo "Usage:" 
	echo "    `basename $0` [-u|-c]"
	echo ""
	echo "	-u  Update application."
	echo "	-c  Reset configuration."
	echo ""
}

while getopts "uc" option; do 
	case "$option" in
		u) admin_option="--update-application" ;;
		c) admin_option="--reset-configuration" ;;
		h) 
			print_usage
			exit 1
			;;
		\?)
      		echo "Invalid option: -$OPTARG" >&2
      		exit 1
      		;;
	esac
done

if [ -z "$admin_option" ]; then
	print_usage
	exit 1
fi

$CMD $admin_option
