uploaded
styleCss
^ '
.post .date {
	margin-top: 5px;
	font-size: 0.9em;
	color: #B0B0B0;
	font-style: italic;
}

.post .text h1, 
.post .text h2,
.post .text h3,
.post .text h4,
.post .text h5 { 
	font-size: 1.1em;
}

.post .reference .col-image {
	width: 100px;
	text-align: center;
	vertical-align: center;
}

.post .reference TABLE TR TD {
	vertical-align: top;
	padding-right: 5px;
}

.post .reference IMG { 
	max-width: 96px;
	max-height: 72px;
	display: inline;
}

.footer { 
	margin-top: 25px;
	font-size: smaller;
	text-align: center;
	color: #c0c0c0;
}
'