Class {
	#name : #WLCronoGtkDarkConfiguration,
	#superclass : #WLCronoGtkConfiguration,
	#category : #'WorkLog-Client-Spec'
}

{ #category : #accessing }
WLCronoGtkDarkConfiguration >> macThemeName [
		
	^ 'Sierra-dark'
]

{ #category : #accessing }
WLCronoGtkDarkConfiguration >> unixThemeName [

	^ 'Adwaita-dark'
]

{ #category : #accessing }
WLCronoGtkDarkConfiguration >> windowsThemeName [

	^ 'Windows-10-Dark-master'
]
